@startjson emr-bundle
{
  "resourceType" : "Bundle",
  "id" : "EMR",
  "type" : "transaction",
  "entry" : [{
    "fullUrl" : "Patient/Covid19PatientExample",
    "resource" : {
      "resourceType" : "Patient",
      "id" : "Covid19PatientExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/covid19-casereporting/StructureDefinition/covid19-patient"]
      },
      "identifier" : [{
        "system" : "http://openhie.org/fhir/covid19-casereporting/identifier/passport",
        "value" : "PASSPORT1234567"
      },
      {
        "system" : "http://openhie.org/fhir/covid19-casereporting/identifier/nid",
        "value" : "NAT1234567"
      }],
      "active" : true,
      "name" : [{
        "use" : "official",
        "family" : "Smith",
        "given" : ["Jane",
        "Maria"]
      }],
      "telecom" : [{
        "system" : "phone",
        "value" : "+27825556666"
      },
      {
        "system" : "email",
        "value" : "someone@example.com"
      }],
      "gender" : "female",
      "birthDate" : "1986-06-04",
      "address" : [{
        "city" : "Cape Town",
        "district" : "City of Cape Town",
        "state" : "Western Province",
        "country" : "South Africa"
      }],
      "contact" : [{
        "relationship" : [{
          "coding" : [{
            "system" : "http://terminology.hl7.org/CodeSystem/v2-0131",
            "code" : "N"
          }]
        }],
        "name" : {
          "family" : "Doe",
          "given" : ["John"]
        },
        "telecom" : [{
          "system" : "phone",
          "value" : "+27829999999"
        }]
      }],
      "managingOrganization" : {
        "reference" : "Organization/Covid19OrganizationExample"
      }
    },
    "request" : {
      "method" : "PUT",
      "url" : "Patient/Covid19PatientExample"
    }
  },
  {
    "fullUrl" : "Encounter/Covid19AssessmentEncounterExample",
    "resource" : {
      "resourceType" : "Encounter",
      "id" : "Covid19AssessmentEncounterExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/covid19-casereporting/StructureDefinition/covid19-encounter"]
      },
      "extension" : [{
        "url" : "http://openhie.org/fhir/covid19-casereporting/StructureDefinition/covid19-next-vaccination",
        "valueDateTime" : "2022-07-28"
      },
      {
        "url" : "http://openhie.org/fhir/covid19-casereporting/StructureDefinition/covid19-ever-hospitalised",
        "valueCodeableConcept" : {
          "coding" : [{
            "system" : "http://snomed.info/sct",
            "code" : "373066001"
          }]
        }
      },
      {
        "url" : "http://openhie.org/fhir/covid19-casereporting/StructureDefinition/covid19-date-last-hospitalised",
        "valueDateTime" : "2022-07-28"
      }],
      "status" : "finished",
      "class" : {
        "system" : "http://terminology.hl7.org/CodeSystem/v3-ActCode",
        "code" : "SS"
      },
      "subject" : {
        "reference" : "Patient/Covid19PatientExample"
      },
      "period" : {
        "start" : "2022-07-28",
        "end" : "2022-08-15"
      },
      "location" : [{
        "location" : {
          "reference" : "Location/Covid19AdmissionLocationExample"
        },
        "physicalType" : {
          "coding" : [{
            "system" : "http://snomed.info/sct",
            "code" : "225746001"
          }]
        }
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "Encounter/Covid19AssessmentEncounterExample"
    }
  },
  {
    "fullUrl" : "Location/Covid19AdmissionLocationExample",
    "resource" : {
      "resourceType" : "Location",
      "id" : "Covid19AdmissionLocationExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/covid19-casereporting/StructureDefinition/covid19-admission-location"]
      },
      "name" : "Covid19 Location",
      "address" : {
        "city" : "Example city 1",
        "district" : "Example district 1",
        "state" : "Example state 1",
        "country" : "Example country 1"
      }
    },
    "request" : {
      "method" : "PUT",
      "url" : "Location/Covid19AdmissionLocationExample"
    }
  },
  {
    "fullUrl" : "Observation/Covid19PresentingSymptomsExample",
    "resource" : {
      "resourceType" : "Observation",
      "id" : "Covid19PresentingSymptomsExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/covid19-casereporting/StructureDefinition/covid19-presenting-symptoms"]
      },
      "status" : "final",
      "code" : {
        "coding" : [{
          "system" : "http://snomed.info/sct",
          "code" : "21522001"
        }]
      },
      "subject" : {
        "reference" : "Patient/Covid19PatientExample"
      },
      "encounter" : {
        "reference" : "Encounter/Covid19AssessmentEncounterExample"
      },
      "effectiveDateTime" : "2022-07-28",
      "performer" : [{
        "reference" : "Organization/Covid19OrganizationExample"
      }],
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/Covid19OrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "Other symptoms here"
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "Observation/Covid19PresentingSymptomsExample"
    }
  },
  {
    "fullUrl" : "Condition/Covid19DiagnosisExample",
    "resource" : {
      "resourceType" : "Condition",
      "id" : "Covid19DiagnosisExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/covid19-casereporting/StructureDefinition/covid19-diagnosis"]
      },
      "verificationStatus" : {
        "coding" : [{
          "system" : "http://terminology.hl7.org/CodeSystem/condition-ver-status",
          "code" : "confirmed"
        }]
      },
      "subject" : {
        "reference" : "Patient/Covid19PatientExample"
      },
      "encounter" : {
        "reference" : "Encounter/Covid19AssessmentEncounterExample"
      },
      "onsetDateTime" : "2022-07-28",
      "recordedDate" : "2022-07-28",
      "evidence" : [{
        "code" : [{
          "coding" : [{
            "system" : "http://snomed.info/sct",
            "code" : "84387000"
          }]
        }]
      }],
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/Covid19OrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "additional notes here"
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "Condition/Covid19DiagnosisExample"
    }
  },
  {
    "fullUrl" : "Condition/Covid19ConditionsOrComorbidityExample",
    "resource" : {
      "resourceType" : "Condition",
      "id" : "Covid19ConditionsOrComorbidityExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/covid19-casereporting/StructureDefinition/covid19-conditions-or-comorbidities"]
      },
     
      "extension" : [{
        "url" : "http://openhie.org/fhir/covid19-casereporting/StructureDefinition/covid19-conditions-or-comorbidities-present",
        "valueCodeableConcept" : {
          "coding" : [{
            "system" : "http://snomed.info/sct",
            "code" : "373066001"
          }]
        }
      }],
      "code" : {
        "coding" : [{
          "system" : "http://snomed.info/sct",
          "code" : "49601007"
        }]
      },
      "subject" : {
        "reference" : "Patient/Covid19PatientExample"
      },
      "encounter" : {
        "reference" : "Encounter/Covid19AssessmentEncounterExample"
      },
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/Covid19OrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "Other conditionss or comorbidities here"
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "Condition/Covid19ConditionsOrComorbidityExample"
    }
  },
  {
    "fullUrl" : "Immunization/Covid19AssessmentVaccinationExample",
    "resource" : {
      "resourceType" : "Immunization",
      "id" : "Covid19AssessmentVaccinationExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/covid19-casereporting/StructureDefinition/covid19-assessment-vaccination"]
      },
    
      "status" : "completed",
      "vaccineCode" : {
        "coding" : [{
          "system" : "http://icd.who.int/icd11/mms",
          "code" : "XM8NQ0"
        }]
      },
      "patient" : {
        "reference" : "Patient/Covid19PatientExample"
      },
      "encounter" : {
        "reference" : "Encounter/Covid19AssessmentEncounterExample"
      },
      "occurrenceDateTime" : "2022-07-28",
      "reportOrigin" : {
        "coding" : [{
          "system" : "http://openhie.org/fhir/covid19-casereporting/CodeSystem/cs-source-of-info",
          "code" : "VaccineCard"
        }]
      },
      "lotNumber" : "1",
      "expirationDate" : "2022-12-28",
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/Covid19OrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "Some other text..."
      }],
      "protocolApplied" : [{
        "series" : "Primary",
        "doseNumberPositiveInt" : 1
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "Immunization/Covid19AssessmentVaccinationExample"
    }
  },
  {
    "fullUrl" : "Immunization/Covid19VaccinationExample",
    "resource" : {
      "resourceType" : "Immunization",
      "id" : "Covid19VaccinationExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/covid19-casereporting/StructureDefinition/covid19-vaccination"]
      },
    
      "status" : "completed",
      "vaccineCode" : {
        "coding" : [{
          "system" : "http://icd.who.int/icd11/mms",
          "code" : "XM4YL8"
        }]
      },
      "patient" : {
        "reference" : "Patient/Covid19PatientExample"
      },
      "encounter" : {
        "reference" : "Encounter/Covid19AssessmentEncounterExample"
      },
      "occurrenceDateTime" : "2022-07-28",
      "reportOrigin" : {
        "coding" : [{
          "system" : "http://openhie.org/fhir/covid19-casereporting/CodeSystem/cs-source-of-info",
          "code" : "VaccineCard"
        }]
      },
      "lotNumber" : "1",
      "expirationDate" : "2022-12-28",
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/Covid19OrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "Some other text..."
      }],
      "protocolApplied" : [{
        "series" : "Booster",
        "doseNumberPositiveInt" : 1
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "Immunization/Covid19VaccinationExample"
    }
  },
  {
    "fullUrl" : "MedicationRequest/Covid19MedicationRequestExample",
    "resource" : {
      "resourceType" : "MedicationRequest",
      "id" : "Covid19MedicationRequestExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/covid19-casereporting/StructureDefinition/covid19-medication-request"]
      },
     
      "status" : "active",
      "intent" : "order",
      "medicationCodeableConcept" : {
        "coding" : [{
          "system" : "http://www.nlm.nih.gov/research/umls/rxnorm",
          "code" : "2599543"
        }]
      },
      "subject" : {
        "reference" : "Patient/Covid19PatientExample"
      },
      "encounter" : {
        "reference" : "Encounter/Covid19AssessmentEncounterExample"
      },
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/Covid19OrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "additional notes here"
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "MedicationRequest/Covid19MedicationRequestExample"
    }
  },
  {
    "fullUrl" : "Observation/Covid19VaccineDoseEverReceivedExample",
    "resource" : {
      "resourceType" : "Observation",
      "id" : "Covid19VaccineDoseEverReceivedExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/covid19-casereporting/StructureDefinition/covid19-vaccine-dose-ever-received"]
      },
    
      "status" : "final",
      "code" : {
        "coding" : [{
          "system" : "http://snomed.info/sct",
          "code" : "373066001"
        }]
      },
      "subject" : {
        "reference" : "Patient/Covid19PatientExample"
      },
      "encounter" : {
        "reference" : "Encounter/Covid19AssessmentEncounterExample"
      },
      "performer" : [{
        "reference" : "Organization/Covid19OrganizationExample"
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "Observation/Covid19VaccineDoseEverReceivedExample"
    }
  },
  {
    "fullUrl" : "Observation/Covid19RecoveredOrSymptomsResolvedExample",
    "resource" : {
      "resourceType" : "Observation",
      "id" : "Covid19RecoveredOrSymptomsResolvedExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/covid19-casereporting/StructureDefinition/covid19-recovered-or-symptoms-resolved"]
      },
     
      "status" : "final",
      "code" : {
        "coding" : [{
          "system" : "http://snomed.info/sct",
          "code" : "370996005"
        }]
      },
      "subject" : {
        "reference" : "Patient/Covid19PatientExample"
      },
      "encounter" : {
        "reference" : "Encounter/Covid19AssessmentEncounterExample"
      },
      "effectiveDateTime" : "2022-11-09",
      "performer" : [{
        "reference" : "Organization/Covid19OrganizationExample"
      }],
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/Covid19OrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "Some other text..."
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "Observation/Covid19RecoveredOrSymptomsResolvedExample"
    }
  },
  {
    "fullUrl" : "Observation/Covid19DeathExample",
    "resource" : {
      "resourceType" : "Observation",
      "id" : "Covid19DeathExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/covid19-casereporting/StructureDefinition/covid19-death"]
      },
     
      "status" : "final",
      "code" : {
        "coding" : [{
          "system" : "http://snomed.info/sct",
          "code" : "419099009"
        }]
      },
      "subject" : {
        "reference" : "Patient/Covid19PatientExample"
      },
      "encounter" : {
        "reference" : "Encounter/Covid19AssessmentEncounterExample"
      },
      "effectiveDateTime" : "2022-11-09",
      "performer" : [{
        "reference" : "Organization/Covid19OrganizationExample"
      }],
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/Covid19OrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "Some other text..."
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "Observation/Covid19DeathExample"
    }
  },
  {
    "fullUrl" : "Observation/Covid19LongCovidPostCovidExample",
    "resource" : {
      "resourceType" : "Observation",
      "id" : "Covid19LongCovidPostCovidExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/covid19-casereporting/StructureDefinition/covid19-long-covid-post-covid"]
      },
    
      "status" : "final",
      "code" : {
        "coding" : [{
          "system" : "http://snomed.info/sct",
          "code" : "1119303003"
        }]
      },
      "subject" : {
        "reference" : "Patient/Covid19PatientExample"
      },
      "encounter" : {
        "reference" : "Encounter/Covid19AssessmentEncounterExample"
      },
      "effectiveDateTime" : "2022-11-09",
      "performer" : [{
        "reference" : "Organization/Covid19OrganizationExample"
      }],
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/Covid19OrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "Some other text..."
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "Observation/Covid19LongCovidPostCovidExample"
    }
  }]
}

@endjson