@startjson emr-bundle
{
  "resourceType" : "Bundle",
  "id" : "EMR",
  "type" : "transaction",
  "entry" : [{
    "fullUrl" : "Patient/HIVPatientExample",
    "resource" : {
      "resourceType" : "Patient",
      "id" : "HIVPatientExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/hiv-cbs/StructureDefinition/hiv-patient"]
      },
     
      "extension" : [{
        "url" : "http://openhie.org/fhir/hiv-cbs/StructureDefinition/key-population-status",
        "valueCodeableConcept" : {
          "coding" : [{
            "system" : "http://snomed.info/sct",
            "code" : "417284009"
          }]
        }
      }],
      "identifier" : [{
        "type" : {
          "coding" : [{
            "system" : "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code" : "MR"
          }]
        },
        "system" : "http://openhie.org/fhir/hiv-cbs/identifier/mr",
        "value" : "ORG1-0765712"
      },
      {
        "system" : "http://openhie.org/fhir/hiv-cbs/identifier/nid",
        "value" : "NID1234567"
      }],
      "active" : true,
      "name" : [{
        "use" : "official",
        "family" : "Smith",
        "given" : ["Jane",
        "Maria"]
      }],
      "telecom" : [{
        "system" : "phone",
        "value" : "+27821234567"
      },
      {
        "system" : "email",
        "value" : "someone@example.com"
      }],
      "gender" : "female",
      "birthDate" : "1990-12-12",
      "address" : [{
        "city" : "Cape Town",
        "district" : "City of Cape Town",
        "state" : "Western Province",
        "country" : "South Africa"
      }],
      "maritalStatus" : {
        "coding" : [{
          "system" : "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
          "code" : "M"
        }]
      },
      "contact" : [{
        "relationship" : [{
          "coding" : [{
            "system" : "http://terminology.hl7.org/CodeSystem/v2-0131",
            "code" : "N"
          }]
        }],
        "name" : {
          "family" : "Doe",
          "given" : ["John"]
        },
        "telecom" : [{
          "system" : "phone",
          "value" : "+27829999999"
        }]
      }],
      "managingOrganization" : {
        "reference" : "Organization/HIVOrganizationExample"
      }
    },
    "request" : {
      "method" : "PUT",
      "url" : "Patient/HIVPatientExample"
    }
  },
  {
    "fullUrl" : "Encounter/TargetFacilityEncounterExample",
    "resource" : {
      "resourceType" : "Encounter",
      "id" : "TargetFacilityEncounterExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/hiv-cbs/StructureDefinition/target-facility-encounter"]
      },
   
      "extension" : [{
        "url" : "http://openhie.org/fhir/hiv-cbs/StructureDefinition/hiv-care-next-visit",
        "valueDateTime" : "2022-10-22"
      }],
      "status" : "finished",
      "class" : {
        "system" : "http://terminology.hl7.org/CodeSystem/v3-ActCode",
        "code" : "AMB"
      },
      "subject" : {
        "reference" : "Patient/HIVPatientExample"
      },
      "episodeOfCare" : [{
        "reference" : "EpisodeOfCare/HIVEpisodeOfCareExample"
      }],
      "period" : {
        "start" : "2022-12-01",
        "end" : "2023-01-20"
      },
      "serviceProvider" : {
        "reference" : "Organization/HIVOrganizationExample"
      },
      "partOf" : {
        "reference" : "Encounter/TransferringFacilityEncounterExample"
      }
    },
    "request" : {
      "method" : "PUT",
      "url" : "Encounter/TargetFacilityEncounterExample"
    }
  },
  {
    "fullUrl" : "Encounter/TransferringFacilityEncounterExample",
    "resource" : {
      "resourceType" : "Encounter",
      "id" : "TransferringFacilityEncounterExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/hiv-cbs/StructureDefinition/transferring-facility-encounter"]
      },
    
      "status" : "finished",
      "class" : {
        "system" : "http://terminology.hl7.org/CodeSystem/v3-ActCode",
        "code" : "AMB"
      },
      "period" : {
        "start" : "2022-12-01",
        "end" : "2023-01-20"
      },
      "serviceProvider" : {
        "reference" : "Organization/HIVOrganizationExample"
      }
    },
    "request" : {
      "method" : "PUT",
      "url" : "Encounter/TransferringFacilityEncounterExample"
    }
  },
  {
    "fullUrl" : "Condition/HIVDiagnosisExample",
    "resource" : {
      "resourceType" : "Condition",
      "id" : "HIVDiagnosisExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/hiv-cbs/StructureDefinition/hiv-diagnosis"]
      },
     
      "identifier" : [{
        "type" : {
          "coding" : [{
            "system" : "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code" : "PI"
          }]
        },
        "system" : "http://openhie.org/fhir/hiv-cbs/identifier/hiv-diagnosis",
        "value" : "abc123"
      }],
      "clinicalStatus" : {
        "coding" : [{
          "system" : "http://terminology.hl7.org/CodeSystem/condition-clinical",
          "code" : "active"
        }]
      },
      "verificationStatus" : {
        "coding" : [{
          "system" : "http://terminology.hl7.org/CodeSystem/condition-ver-status",
          "code" : "confirmed"
        }]
      },
      "code" : {
        "coding" : [{
          "system" : "http://snomed.info/sct",
          "code" : "86406008"
        }]
      },
      "subject" : {
        "reference" : "Patient/HIVPatientExample"
      },
      "encounter" : {
        "reference" : "Encounter/TargetFacilityEncounterExample"
      },
      "recordedDate" : "2021-05-18",
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/HIVOrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "Additional information regarding the HIV diagnosis"
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "Condition/HIVDiagnosisExample"
    }
  },
  {
    "fullUrl" : "Observation/DeathExample",
    "resource" : {
      "resourceType" : "Observation",
      "id" : "DeathExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/hiv-cbs/StructureDefinition/death"]
      },
    
      "status" : "final",
      "code" : {
        "coding" : [{
          "system" : "http://snomed.info/sct",
          "code" : "419620001"
        }]
      },
      "subject" : {
        "reference" : "Patient/HIVPatientExample"
      },
      "encounter" : {
        "reference" : "Encounter/TargetFacilityEncounterExample"
      },
      "effectiveDateTime" : "2023-02-05",
      "valueCodeableConcept" : {
        "coding" : [{
          "system" : "http://loinc.org",
          "code" : "80359-3"
        }]
      },
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/HIVOrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "Details regarding death"
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "Observation/DeathExample"
    }
  },
  {
    "fullUrl" : "Observation/DateHIVTestDoneExample",
    "resource" : {
      "resourceType" : "Observation",
      "id" : "DateHIVTestDoneExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/hiv-cbs/StructureDefinition/date-hiv-test-done"]
      },
    
      "status" : "final",
      "code" : {
        "coding" : [{
          "system" : "http://snomed.info/sct",
          "code" : "315124004"
        }]
      },
      "subject" : {
        "reference" : "Patient/HIVPatientExample"
      },
      "encounter" : {
        "reference" : "Encounter/TargetFacilityEncounterExample"
      },
      "effectiveDateTime" : "2022-12-10",
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/HIVOrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "Additional information regarding the HIV test"
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "Observation/DateHIVTestDoneExample"
    }
  },
  {
    "fullUrl" : "EpisodeOfCare/HIVEpisodeOfCareExample",
    "resource" : {
      "resourceType" : "EpisodeOfCare",
      "id" : "HIVEpisodeOfCareExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/hiv-cbs/StructureDefinition/hiv-episode-of-care"]
      },
     
      "identifier" : [{
        "type" : {
          "coding" : [{
            "system" : "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code" : "PI"
          }]
        },
        "system" : "http://openhie.org/fhir/hiv-cbs/identifier/enrollment-unique-id",
        "value" : "abc123"
      }],
      "status" : "active",
      "diagnosis" : [{
        "condition" : {
          "reference" : "Condition/HIVDiagnosisExample"
        }
      }],
      "patient" : {
        "reference" : "Patient/HIVPatientExample"
      },
      "managingOrganization" : {
        "reference" : "Organization/HIVOrganizationExample"
      },
      "period" : {
        "start" : "2021-05-18",
        "end" : "2021-05-18"
      }
    },
    "request" : {
      "method" : "PUT",
      "url" : "EpisodeOfCare/HIVEpisodeOfCareExample"
    }
  },
  {
    "fullUrl" : "Observation/HIVRecencyTestDoneExample",
    "resource" : {
      "resourceType" : "Observation",
      "id" : "HIVRecencyTestDoneExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/hiv-cbs/StructureDefinition/hiv-recency-test-done"]
      },
    
      "status" : "final",
      "code" : {
        "coding" : [{
          "system" : "http://snomed.info/sct",
          "code" : "409788009"
        }]
      },
      "subject" : {
        "reference" : "Patient/HIVPatientExample"
      },
      "encounter" : {
        "reference" : "Encounter/TargetFacilityEncounterExample"
      },
      "effectiveDateTime" : "2022-12-10",
      "valueCodeableConcept" : {
        "coding" : [{
          "system" : "http://snomed.info/sct",
          "code" : "373066001"
        }]
      },
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/HIVOrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "Additional information regarding the HIV recency test"
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "Observation/HIVRecencyTestDoneExample"
    }
  },
  {
    "fullUrl" : "Observation/HIVRecencyTestResultExample",
    "resource" : {
      "resourceType" : "Observation",
      "id" : "HIVRecencyTestResultExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/hiv-cbs/StructureDefinition/hiv-recency-test-result"]
      },
    
      "status" : "final",
      "code" : {
        "coding" : [{
          "system" : "http://snomed.info/sct",
          "code" : "409788009"
        }]
      },
      "subject" : {
        "reference" : "Patient/HIVPatientExample"
      },
      "encounter" : {
        "reference" : "Encounter/TargetFacilityEncounterExample"
      },
      "effectiveDateTime" : "2022-12-10",
      "performer" : [{
        "reference" : "Organization/HIVOrganizationExample"
      }],
      "valueCodeableConcept" : {
        "coding" : [{
          "system" : "http://snomed.info/sct",
          "code" : "118246004"
        }]
      },
      "interpretation" : [{
        "coding" : [{
          "system" : "http://snomed.info/sct",
          "code" : "6493001"
        }]
      }],
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/HIVOrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "Additional information regarding the HIV recency test result"
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "Observation/HIVRecencyTestResultExample"
    }
  },
  {
    "fullUrl" : "Observation/CD4PercentageExample",
    "resource" : {
      "resourceType" : "Observation",
      "id" : "CD4PercentageExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/hiv-cbs/StructureDefinition/hiv-cd4-percentage"]
      },
     
      "status" : "final",
      "code" : {
        "coding" : [{
          "system" : "http://snomed.info/sct",
          "code" : "313938009"
        }]
      },
      "subject" : {
        "reference" : "Patient/HIVPatientExample"
      },
      "encounter" : {
        "reference" : "Encounter/TargetFacilityEncounterExample"
      },
      "effectiveDateTime" : "2022-12-10",
      "performer" : [{
        "reference" : "Organization/HIVOrganizationExample"
      }],
      "valueQuantity" : {
        "value" : 45.23
      },
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/HIVOrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "Additional information regarding the CD4 Percentage"
      }],
      "derivedFrom" : [{
        "reference" : "Observation/CD4TestResultExample"
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "Observation/CD4PercentageExample"
    }
  },
  {
    "fullUrl" : "Observation/CD4TestResultExample",
    "resource" : {
      "resourceType" : "Observation",
      "id" : "CD4TestResultExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/hiv-cbs/StructureDefinition/hiv-cd4-test"]
      },
    
      "status" : "final",
      "code" : {
        "coding" : [{
          "system" : "http://snomed.info/sct",
          "code" : "151271000119102"
        }]
      },
      "subject" : {
        "reference" : "Patient/HIVPatientExample"
      },
      "encounter" : {
        "reference" : "Encounter/TargetFacilityEncounterExample"
      },
      "effectiveDateTime" : "2022-12-10",
      "performer" : [{
        "reference" : "Organization/HIVOrganizationExample"
      }],
      "valueInteger" : 650,
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/HIVOrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "Additional information regarding the CD4 Count"
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "Observation/CD4TestResultExample"
    }
  },
  {
    "fullUrl" : "CarePlan/ARVTreatmentRegimenSwitchedOrSubstitutedExample",
    "resource" : {
      "resourceType" : "CarePlan",
      "id" : "ARVTreatmentRegimenSwitchedOrSubstitutedExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/hiv-cbs/StructureDefinition/hiv-arv-treatment"]
      },
    
      "status" : "active",
      "intent" : "plan",
      "subject" : {
        "reference" : "Patient/HIVPatientExample"
      },
      "encounter" : {
        "reference" : "Encounter/TargetFacilityEncounterExample"
      },
      "period" : {
        "start" : "2022-12-01",
        "end" : "2022-12-01"
      },
      "activity" : [{
        "detail" : {
          "extension" : [{
            "url" : "http://openhie.org/fhir/hiv-cbs/StructureDefinition/art-regimen-line",
            "valueCodeableConcept" : {
              "coding" : [{
                "system" : "http://snomed.info/sct",
                "code" : "708255002"
              }]
            }
          },
          {
            "url" : "http://openhie.org/fhir/hiv-cbs/StructureDefinition/art-regimen-switched-or-substituted",
            "valueCodeableConcept" : {
              "coding" : [{
                "system" : "http://openhie.org/fhir/hiv-cbs/CodeSystem/cs-art-regimen-change-type",
                "code" : "Switched"
              }]
            }
          }],
          "kind" : "MedicationRequest",
          "code" : {
            "coding" : [{
              "system" : "http://loinc.org",
              "code" : "45260-7"
            }]
          },
          "status" : "in-progress",
          "productCodeableConcept" : {
            "coding" : [{
              "system" : "http://snomed.info/sct",
              "code" : "387005008"
            }]
          }
        }
      }],
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/HIVOrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "Additional information regarding the switching of the ARV regimen with another ARV regimen."
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "CarePlan/ARVTreatmentRegimenSwitchedOrSubstitutedExample"
    }
  },
  {
    "fullUrl" : "MedicationRequest/HIVCareMedicationRequestExample",
    "resource" : {
      "resourceType" : "MedicationRequest",
      "id" : "HIVCareMedicationRequestExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/hiv-cbs/StructureDefinition/hiv-med-req"]
      },
     
      "status" : "active",
      "intent" : "proposal",
      "medicationCodeableConcept" : {
        "coding" : [{
          "system" : "http://snomed.info/sct",
          "code" : "878898002"
        }]
      },
      "subject" : {
        "reference" : "Patient/HIVPatientExample"
      },
      "encounter" : {
        "reference" : "Encounter/TargetFacilityEncounterExample"
      },
      "basedOn" : [{
        "reference" : "CarePlan/ARVTreatmentExample"
      }],
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/HIVOrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "Additional information regarding the HIV Medication Request"
      }],
      "dispenseRequest" : {
        "quantity" : {
          "value" : 30
        }
      }
    },
    "request" : {
      "method" : "PUT",
      "url" : "MedicationRequest/HIVCareMedicationRequestExample"
    }
  },
  {
    "fullUrl" : "ServiceRequest/TransferredOutServiceRequestExample",
    "resource" : {
      "resourceType" : "ServiceRequest",
      "id" : "TransferredOutServiceRequestExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/hiv-cbs/StructureDefinition/transferred-out"]
      },
     
      "status" : "completed",
      "intent" : "order",
      "code" : {
        "coding" : [{
          "system" : "http://loinc.org",
          "code" : "LA20597-3"
        }]
      },
      "subject" : {
        "reference" : "Patient/HIVPatientExample"
      },
      "encounter" : {
        "reference" : "Encounter/TargetFacilityEncounterExample"
      },
      "occurrenceDateTime" : "2012-01-05",
      "requester" : {
        "reference" : "Practitioner/PractitionerExample"
      },
      "performer" : [{
        "reference" : "Organization/HIVOrganizationPatientTransferredToExample"
      }],
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/HIVOrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "additional notes about the transfer"
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "ServiceRequest/TransferredOutServiceRequestExample"
    }
  },
  {
    "fullUrl" : "Organization/HIVOrganizationPatientTransferredToExample",
    "resource" : {
      "resourceType" : "Organization",
      "id" : "HIVOrganizationPatientTransferredToExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/hiv-cbs/StructureDefinition/hiv-organization-patient-transferred-to"]
      },
    
      "identifier" : [{
        "type" : {
          "coding" : [{
            "system" : "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code" : "XX"
          }]
        },
        "system" : "http://openhie.org/fhir/hiv-cbs/identifier/hiv-organization",
        "value" : "facility1"
      }],
      "name" : "HIV Test Services Health Facility",
      "address" : [{
        "line" : ["DISI line 1",
        "DISI line 2",
        "DISI line 3"],
        "city" : "DISI city 1",
        "district" : "DISI district 1",
        "state" : "DISI state 1",
        "postalCode" : "DISI postal code",
        "country" : "DISI country"
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "Organization/HIVOrganizationPatientTransferredToExample"
    }
  },
  {
    "fullUrl" : "Observation/HIVTestResultExample",
    "resource" : {
      "resourceType" : "Observation",
      "id" : "HIVTestResultExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/hiv-cbs/StructureDefinition/hiv-test-results"]
      },
    
      "status" : "final",
      "code" : {
        "coding" : [{
          "system" : "http://snomed.info/sct",
          "code" : "398579006"
        }]
      },
      "subject" : {
        "reference" : "Patient/HIVPatientExample"
      },
      "encounter" : {
        "reference" : "Encounter/TargetFacilityEncounterExample"
      },
      "effectiveDateTime" : "2022-11-30",
      "performer" : [{
        "reference" : "Organization/HIVOrganizationExample"
      }],
      "valueInteger" : 1001,
      "interpretation" : [{
        "coding" : [{
          "system" : "http://snomed.info/sct",
          "code" : "19032002"
        }]
      }],
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/HIVOrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "Viral load not suppressed"
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "Observation/HIVTestResultExample"
    }
  }]
}
@endjson