@startjson lab-order-bundle
{
  "resourceType" : "Bundle",
  "id" : "LabOrder",
  "type" : "transaction",
  "entry" : [{
    "fullUrl" : "Task/HIVLabOrderTaskExample",
    "resource" : {
      "resourceType" : "Task",
      "id" : "HIVLabOrderTaskExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/hiv-cbs/StructureDefinition/hiv-lab-task"]
      },
     
      "identifier" : [{
        "system" : "http://openhie.org/fhir/hiv-cbs/lab-integration/test-order-number",
        "value" : "ORDER12345"
      }],
      "basedOn" : [{
        "reference" : "ServiceRequest/HIVServiceRequestExample"
      }],
      "status" : "requested",
      "intent" : "order",
      "executionPeriod" : {
        "start" : "2022-07-28"
      },
      "lastModified" : "2022-07-28",
      "requester" : {
        "reference" : "Organization/HIVOrganizationExample"
      },
      "owner" : {
        "reference" : "Organization/HIVOrganizationExample"
      },
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/HIVOrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "additional notes here"
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "Task/HIVLabOrderTaskExample"
    }
  },
  {
    "fullUrl" : "Location/HIVServiceRequestLocationExample",
    "resource" : {
      "resourceType" : "Location",
      "id" : "HIVServiceRequestLocationExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/hiv-cbs/StructureDefinition/hiv-service-request-location"]
      },
     
      "identifier" : [{
        "type" : {
          "coding" : [{
            "system" : "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code" : "XX"
          }]
        },
        "system" : "http://openhie.org/fhir/hiv-cbs/identifier/hiv-service-request-location",
        "value" : "facility2"
      }],
      "name" : "Laboratory Services",
      "address" : {
        "line" : ["DISI line 1",
        "DISI line 2",
        "DISI line 3"],
        "city" : "DISI city 1",
        "district" : "DISI district 1",
        "state" : "DISI state 1",
        "postalCode" : "DISI postal code",
        "country" : "DISI country"
      }
    },
    "request" : {
      "method" : "PUT",
      "url" : "Location/HIVServiceRequestLocationExample"
    }
  },
  {
    "fullUrl" : "ServiceRequest/HIVServiceRequestExample",
    "resource" : {
      "resourceType" : "ServiceRequest",
      "id" : "HIVServiceRequestExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/hiv-cbs/StructureDefinition/HIV-lab-order"]
      },
    
      "identifier" : [{
        "type" : {
          "coding" : [{
            "system" : "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code" : "PLAC"
          }]
        },
        "system" : "http://openhie.org/fhir/hiv-cbs/identifier/lab-order-identifier",
        "value" : "ORDER12345"
      }],
      "status" : "completed",
      "intent" : "order",
      "doNotPerform" : false,
      "code" : {
        "coding" : [{
          "system" : "http://loinc.org",
          "code" : "25836-8"
        }]
      },
      "subject" : {
        "reference" : "Patient/HIVPatientExample"
      },
      "encounter" : {
        "reference" : "Encounter/TargetFacilityEncounterExample"
      },
      "occurrenceDateTime" : "2012-01-05",
      "requester" : {
        "reference" : "Practitioner/PractitionerExample"
      },
      "locationReference" : [{
        "reference" : "Location/HIVServiceRequestLocationExample"
      }],
      "reasonCode" : [{
        "coding" : [{
          "system" : "http://snomed.info/sct",
          "code" : "428450006"
        }]
      }],
      "specimen" : [{
        "reference" : "Specimen/VLSpecimenExample"
      }],
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/HIVOrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "additional notes here"
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "ServiceRequest/HIVServiceRequestExample"
    }
  },
  {
    "fullUrl" : "Practitioner/PractitionerExample",
    "resource" : {
      "resourceType" : "Practitioner",
      "id" : "PractitionerExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/hiv-cbs/StructureDefinition/hiv-practitioner"]
      },
    
      "name" : [{
        "family" : "Smith",
        "given" : ["James"]
      }],
      "telecom" : [{
        "system" : "phone",
        "value" : "27537652509"
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "Practitioner/PractitionerExample"
    }
  },
  {
    "fullUrl" : "Specimen/VLSpecimenExample",
    "resource" : {
      "resourceType" : "Specimen",
      "id" : "VLSpecimenExample",
      "meta" : {
        "profile" : ["http://openhie.org/fhir/hiv-cbs/StructureDefinition/viral-load-specimen"]
      },
    
      "identifier" : [{
        "type" : {
          "coding" : [{
            "system" : "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code" : "USID"
          }]
        },
        "system" : "http://openhie.org/fhir/hiv-cbs/identifier/specimen-id",
        "value" : "abc123"
      }],
      "type" : {
        "coding" : [{
          "system" : "http://snomed.info/sct",
          "code" : "119361006"
        }]
      },
      "subject" : {
        "reference" : "Patient/HIVPatientExample"
      },
      "collection" : {
        "collectedDateTime" : "2022-07-28"
      },
      "note" : [{
        "authorReference" : {
          "reference" : "Organization/HIVOrganizationExample"
        },
        "time" : "2015-02-07T13:28:17-05:00",
        "text" : "additional notes here"
      }]
    },
    "request" : {
      "method" : "PUT",
      "url" : "Specimen/VLSpecimenExample"
    }
  }]
}

@endjson