@startuml UseCaseDiagram
left to right direction
actor "Health Professional" as professional
rectangle EMR {
  usecase "Register Client" as UC1
  usecase "ART Regimen Switching" as UC2
  usecase "ART Initiation" as UC3
  usecase "CD4 Results" as UC4
  usecase "Patient Outcome" as UC5
  usecase "Enrolled into Care" as UC6
  usecase "HIV Diagnosis" as UC7
  usecase "Viral Load Results" as UC8
  usecase "Subsequent Sampling" as UC9
  usecase "Submit Lab Order" as UC10
  usecase "HIV Recency Testing" as UC11
}

professional --> UC1
professional --> UC2
professional --> UC3
professional --> UC4
professional --> UC5
professional --> UC6
professional --> UC7
professional --> UC8
professional --> UC10
professional --> UC11

(UC4) <.. (UC9) : "<<extends>>"
(UC8) <.. (UC9) : "<<extends>>"
(UC8) <.. (UC11) : "<<extends>>"


actor "Lab Assistant" as labAssistant
rectangle Laboratory {
  usecase "Sample Collection" as UC14
  usecase "Process Lab Request" as UC15
  usecase "Document Lab Result" as UC16
  usecase "Reject Lab Order" as UC17
  usecase "Cancel Lab Order" as UC18
  usecase "Document Reason For Not Performing Test" as UC19
}

labAssistant --> UC14
labAssistant --> UC15


(UC15) <.. (UC16) : "<<extends>>"
(UC15) <.. (UC17) : "<<extends>>"
(UC15) <.. (UC18) : "<<extends>>"

(UC18) ..> (UC19) : "<<include>>"
(UC17) ..> (UC19) : "<<include>>"

(UC10) ..> Laboratory

(UC16) ..> EMR : "Lab result"

actor "Interoperability Layer" as iol
rectangle "Centralised Data Repository" as cdr {
  usecase "Manage Clinical Data" as UC20
}

iol <--> cdr : "HTTPS"

EMR <..> iol : "EMR data"
Laboratory <..> iol : "Lab data"


actor "Matching Administrator" as macthingAdmin
rectangle "Client Registry" as cr {
  usecase "Manage Master Patient Index (MPI)" as UC21
}

macthingAdmin --> UC21

iol <--> cr : "HTTPS"

actor "Case Reporter" as caseReporter
rectangle "Data Mart" as dm {
  usecase "Generate Reports" as UC22
}

caseReporter --> UC22

cdr --> dm : "Push Data"
cr --> dm : "Push Data"

@enduml
